### ISSUE TITLE
remove unused features from the UI

### ISSUE THREAD

**Issue by mattersoflight** [czbiohub-sf/PhenoSight#23]
@nbathreya, @Soorya19Pradeep  as we I discussed, let's strengthen the accuracy and efficiency of analysis with PhenoSight, and simplify the UI.

Let's remove the UI elements that are not needed for this iteration of the analysis (milestone v0.1.0).

* segmentation tab
* annotation tab
* batch processing in utilities tab (TBD at next meeting).

**Comment by nbathreya** [comment]
All of the suggested UI changes are made and merged onto the main branch.
