### ISSUE TITLE
remove the utilities tab from the GUI

### ISSUE THREAD

**Issue by mattersoflight** [czbiohub-sf/PhenoSight#29]
The utility tab of PhenoSight provides batch execution of segmentation and analysis. Batch segmentation requires some parameters (such as CellPose model, NA for focus finding), that are not exposed. We decided to do the batch segmentation and computation of features with CLI. @nbathreya will hide the utilities tab.

**Comment by nbathreya** [comment]
This is done. Here's the code from main_widget.py to hide the utilities tab:

tab_index = self.ui.tabWidget.indexOf(self.ui.tabWidget.findChild(QWidget, 'tab_4'))
        if tab_index >= 0:
            self.ui.tabWidget.removeTab(tab_index)
