### ISSUE TITLE
decide on the data structure and metadata structure for a zarr store

### ISSUE THREAD

**Issue by mattersoflight** [czbiohub-sf/PhenoSight#3]
At the last meeting, we discussed a possible zarr format to store the data and segmentations in a zarr store, along with annotations in a csv format. 

Steps:
- [x] document the data structure that is compatible with NGFF v0.4, e.g., [data structure documentation for mantis microscope](https://github.com/czbiohub/mantis/blob/main/docs/data_structure.md)
- [x] refactor the `PhenoSight.io` module to depend on `iohub`. The current module seems to be a copy of the `waveOrder.io`.  A convenient refactor may be to use `iohub.read_micromanager` or `iohub.open_ome_zarr` when reading data, and `iohub.open_ome_zarr` when writing data.
- [x] extend the PhenoSight viewer to load data from the new zarr store.

**Comment by mattersoflight** [comment]
Here is data hierarchy documentation for [virtual staining ](https://github.com/mehta-lab/viscy/blob/microdl/viscy/data_organization.md).

**Comment by nbathreya** [comment]
The branch PhenoSight_zarr has implemented all of the above steps. It will be made the main branch.
