### ISSUE TITLE
create/update a shared PhenoSight environment

### ISSUE THREAD

**Issue by mattersoflight** [czbiohub-sf/PhenoSight#8]
Other users will start testing PhenoSight. It is timely to create/ update a shared conda environment. @nbathreya can you create one and post instructions here?

**Comment by nbathreya** [comment]
Steps to use PhenoSight on Bruno:

1. module load anaconda
2. module load comp_micro
3. conda activate /hpc/user_apps/comp_micro/conda_envs/PhenoSight
4. git clone https://github.com/czbiohub-sf/PhenoSight.git
5. cd PhenoSight
6. export PYTHONPATH=${PYTHONPATH}:/path/to/your/directory
7. python run_phenosight.py

**Comment by mattersoflight** [comment]
@nbathreya thanks for setting up the environment. Upon testing, I found that the instructions need a tweak. 

6. export PYTHONPATH=${PYTHONPATH}:/path/to/PhenoSight/PhenoSight.

You can also use `pyproject.toml` to make the PhenoSight [package pip installable](https://python-poetry.org/docs/pyproject/), and register the launch script. 

You can see an example pyproject.toml from `viscy' [here](https://github.com/mehta-lab/viscy). @ziw-liu can say more.

**Comment by ziw-liu** [comment]
Packaging should be relatively straightforward, and I'm happy to answer any questions.

Browsing the repo structure, I also have a related observation that this project is not a napari plugin yet. Usually napari plugins are developed based on the [cookiecutter template](https://github.com/napari/cookiecutter-napari-plugin), so packaging infra comes for free. We may consider making this project NPE-conformant so that things like [napari hub](https://www.napari-hub.org/) could work.

**Comment by mattersoflight** [comment]
PhenoSight, formerly known as infected-cell-annotator, was going to be an internal tool. Hence, the lack of proper packaging. @nbathreya please open another issue to make PhenoSight [npe2](https://napari.org/stable/plugins/npe2_migration_guide.html) compatible. We should work on it after reaching the analysis workflow is fully fleshed out.

**Comment by mattersoflight** [comment]
@nbathreya I see that the main branch currently has an environment file PS.yml. PhenoSight doesn't seem to be a pip installable package at this point. Is this intentional (are you working towards a pypi package?)

**Comment by nbathreya** [comment]
@ziw-liu and I are working on making this a pip installable package. It is still work in progress. Hopefully it'll be resolved by 8/11/23.

**Comment by mattersoflight** [comment]
@nbathreya  the package installation is working per user via pip. So we can close this issue.
